### ISSUE TITLE
Fatal error při pokusu o aktivaci

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#1]
Plugin nemůže být aktivován, protože způsobil závažnou chybu.

Fatal error: Uncaught Exception: Pro správnou funkčnost zadejte v nastavení pluginu SkautIS přidělené APP ID in /home/vu009217/www/wp-content/plugins/skautis-integration/src/auth/SkautisGateway.php:54 Stack trace: #0 /home/vu009217/tmp/ProxyManagerGeneratedProxy__PM__SkautisIntegrationAuthSkautisGatewayGeneratedf5947a5bb1a214acfb4063d123db7421.php(44): SkautisIntegration\Auth\SkautisGateway->getSkautisInstance() #1 /home/vu009217/www/wp-content/plugins/skautis-integration/src/admin/Admin.php(35): ProxyManagerGeneratedProxy\__PM__\SkautisIntegration\Auth\SkautisGateway\Generatedf5947a5bb1a214acfb4063d123db7421->getSkautisInstance() #2 /home/vu009217/www/wp-content/plugins/skautis-integration/src/admin/Admin.php(25): SkautisIntegration\Admin\Admin->initHooks() #3 /home/vu009217/www/wp-content/plugins/skautis-integration/src/services/services.php(88): SkautisIntegration\Admin\Admin->__construct(Object(SkautisIntegration\Admin\Settings), Object(SkautisIntegration\Admin\Users), Object(SkautisIntegration\Admin\UsersManage in /home/vu009217/www/wp-content/plugins/skautis-integration/src/auth/SkautisGateway.php on line 54

**Comment by davidulus** [comment]
# fixnuto
