### ISSUE TITLE
Nefunguje MultiSITE

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#10]
Při síťové aktivaci nefungují záložky Přihlašování, Moduly a Správa uživatelů. Není to tedy stále funkční :-(

**Comment by kalich5** [comment]
Ani při aktivaci na každém webu to nefunguje. Pořád stejná hláška

`Sorry, you are not allowed to access this page.`

**Comment by davidulus** [comment]
Ověř jen prosím, že tam máš aktuální verzi (ne z releases, tam to ještě není). V plugins\skautis-integration\vendor by měly být jen 3 složky a jeden soubor.

**Comment by kalich5** [comment]
Dal jsem stáhnout celý balíček znova. Přímo jak je v repizitáři vpravo zelené tlačítko pro stažení. A ano, mám tam jen ty 3 složky a jeden soubor. Releases nestahuju.

**Comment by davidulus** [comment]
Vůbec se mi to nedaří nasimulovat. Hází Ti to něco do debug.log? Zkoušel jsi to na čisté instalaci WP s multisite?

**Comment by kalich5** [comment]
ani na klasické instalaci WP mi to hazí stejné chyby

**Comment by kalich5** [comment]
Tenhle balíček používám

[skautis-integration.zip](https://github.com/skaut/skautis-integration/files/1106611/skautis-integration.zip)

**Comment by davidulus** [comment]
"ani na klasické instalaci WP to nefunguje hazí to stejné chyby" - myslíš tím mimo multisite? Úplně klasickou běžnou instalaci?

**Comment by kalich5** [comment]
ano, myslím tím obyčejný WP, žádnou multisite

**Comment by davidulus** [comment]
Na tom webu http://wordpress-test.michaljanata.cz/ je obecně něco rozbitého, protože se nedostaneš na admin page ani pluginu Advanced Automatic Updates (http://wordpress-test.michaljanata.cz/wp-admin/options-general.php?page=automatic-updater)

**Comment by kalich5** [comment]
Fakt jo, no podobný probém mám i na dalších webech u Wedosu :-( zkusím to ještě na Lebedě

**Comment by kalich5** [comment]
Na lebedě na MultiSIte to jede. Problém je tedy u mě.
