### ISSUE TITLE
REST API chyba

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#108]
REST API je jeden ze způsobů, jak WordPress a další aplikace komunikují se serverem. Jedním z příkladů je obrazovka editoru, která se o toto API opírá při zobrazování a ukládání příspěvků a stránek.
REST API požadavek selhal z důvodu chyby.
Chyba: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (http_request_failed)

**Comment by marekdedic** [comment]
Vyřešeno v #106
