### ISSUE TITLE
Sady pravidel - "Všichni bez omezení"

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#12]
Šlo by po jendom použití strýt podmínku "Všichni bez omezení"? Aby si tam omylem někdo nevytvořil víc takových pravidel.

Nebo jen špatně chápu použití...

**Comment by davidulus** [comment]
Implementačně by to bylo trochu nepříjemné, ale možné to samozřejmě je. Jen v tom tedy nevidím moc smysl :-) Ze stejné logiky bychom pak mohli znemožnit zadávání duplicitních podmínek, které by se kryly. Tohle už je prostě na uživateli. Když si dá do 3 pravidel, že se mohou registrovat všichni, tak ať - podle toho se to taky bude chovat.
Spíš přemýšlím, zda to nějak nepřejmenovat či jinak upravit, aby nebyla tendence vytvářet pravidla typu:
Typ členství : není nečlen
A jinak se mohou registrovat všichni.
Asi by stačilo nějaké description k tomu pravidlu.

**Comment by davidulus** [comment]
Pojďme to nějak rozseknout :-) Udělal jsem nějaký nástřel, dolaďme jej.

**Comment by kalich5** [comment]
Už to nasazuju, problém je že bez dalších služeb skautISu se to nezobrazí. 

A ten popis mi přijde v pohodě. Když tak se může časem změnit.
