### ISSUE TITLE
Opověď z WordPress.org - Dokážeme to zapracovat?

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#13]
There are issues with your plugin code.

 Please read this ENTIRE email, address all listed issues, and reply to this email with your corrected code attached. It is required for you to read and reply to these emails, and failure to do so will result in significant delays with your plugin being accepted.

 Also please remember in addition to code quality, security and functionality, we require all plugins adhere to our guidelines. If you have not yet, please read them:

 * https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

 ## Please sanitize, escape, and validate your POST calls

 When you include POST/GET/REQUEST calls in your plugin, it's important to sanitize, validate, and escape them. The goal here is to prevent a user from accidentally sending trash data through the system, as well as protecting them from potential security issues.

 SANITIZE: All instances where generated content is inserted into the database, or into a file, or being otherwise processed by WordPress, the data MUST be properly sanitized for security. By sanitizing your POST data when used to make action calls or URL redirects, you will lessen the possibility of XSS vulnerabilities. You should never have a raw data inserted into the database, even by a update function, and even with a prepare() call.

 VALIDATE: In addition to sanitization, you should validate all your calls. If a $_POST call should only be a number, ensure it's an int() before you pass it through anything. Even if you're sanitizing or using WordPress functions to ensure things are safe, we ask you please validate for sanity's sake. Any time you are adding data to the database, it should be the right data.

 ESCAPE: Similarly, when you're outputting data, make sure to escape it properly, so it can't hijack admin screens. There are many esc_*() functions you can use to make sure you don't show people the wrong data.

 In all cases, using stripslashes or strip_tags is not enough. You need to use the most appropriate method associated with the type of content you're processing. Check that a URL is a URL and don't just be lazy and use sanitize_text please. The ultimate goal is that you should ensure that invalid and unsafe data is NEVER processed or displayed. Clean everything, check everything, escape everything, and never trust the users to always have input sane data.

 Please review this document and update your code accordingly: http://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data

 Exampel:

 update_user_meta( $userId, 'skautisUserId_prod', $_POST['skautisUserId_prod'] );

 and

 $returnUrl = $_GET['ReturnUrl'];

 ## Including your own CURL code

 WordPress comes with an extensive HTTP API that should be used instead of creating your own curl calls. It’s both faster and more extensive. It’ll fall back to curl if it has to, but it’ll use a lot of WordPress’ native functionality first.

https://developer.wordpress.org/plugins/http-api/

 ----

 Please make sure you've addressed ALL issues brought up in this email. When you've corrected your code, reply to this email with the updated code attached as a zip, or provide a link to the new code for us to review. If you use gmail, you won’t be able to send a ZIP file if it contains any JS files (yes, we know it’s stupid, blame Google).

 If you have questions, concerns, or need clarification, please reply to this email and just ask us.

 (While we have tried to make this review as exhaustive as possible we, like you, are humans and may have missed things. As such, we will re-review the ENTIRE plugin when you send it back to us. We appreciate your patience and understanding in this.)

**Comment by davidulus** [comment]
Jop, no problem. Budu hodný a nebudu ani příliš diskutovat o zbytečnosti těch konkrétních navržených sanitizací :-) Všude, kde je byť minimální riziko kompromitování přijatých dat, je sanitizace jak na vstupu tak na výstupu. Např. update_user_meta používá funkci update_metadata kam mohou výslovně dle dokumentace přijít čisté RAW vstupy, protože v ní následně probíhá sanitizace interně (pro jistotu jsem ověřil i v jádře a je to tak).
Ale raději dvakrát sanitizovat než to jednou někde zapomenout, že ;-)

Zkusím ty CRONy přepsat na WP HTTP API, ale na začátku jsem je zavrhl, protože jsem potřeboval dost specifický přístup, aby byl skautIS ochotný se odhlásit jen přes CRON a nebylo třeba tam přesměrovávat uživatele. Umožnilo to vrátit jej na stránku, kde se odhlašoval, což by při přesměrování na skautIS odhlášení nebylo možné, protože při odhlašovvání ignoruje ReturnUrl.

**Comment by kalich5** [comment]
Super, hned jak bude nová verze pošlu jim to zpátky. Máš odhad?

**Comment by davidulus** [comment]
Snad už zítra.

**Comment by kalich5** [comment]
super :+1:

**Comment by kalich5** [comment]
Aktuální verze stažena a odeslána na kontrolu na WP.org
