### ISSUE TITLE
Neodchycená chyba v pluginu.

### ISSUE THREAD

**Issue by vairad** [skaut/skautis-integration#141]
Ahoj,
wordpress mi hlásí error při zpracovávání propojení uživatele WP se SkautIS.
V rámci GUI při pokusu o propojení uživatele SkautIS s uživatelem WP se nic nestane a WP pošle mail o chybě v systému:

Při hledání pomoci s tímto problémem, můžete být požádáni o některé z následujících informací:

WordPress verze 5.8.1
Aktuální šablona: Twenty Twenty (verze 1.8)
Aktuální plugin: skautIS integration (verze 1.1.22)
Verze PHP 7.4.24

Podrobnosti chyby
=================
Na řádku č. 216 v souboru /home/vu008524/www/wp-content/plugins/skautis-integration/src/modules/Register/WpRegister.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Error: Call to undefined function SkautisIntegration\Modules\Register\add_query_arurlg() in /home/vu008524/www/wp-content/plugins/skautis-integration/src/modules/Register/WpRegister.php:216
Stack trace:
#0 /home/vu008524/www/wp-content/plugins/skautis-integration/src/admin/UsersManagement.php(241): SkautisIntegration\Modules\Register\WpRegister->getManuallyRegisterWpUserUrl()
#1 /home/vu008524/www/wp-includes/class-wp-hook.php(303): SkautisIntegration\Admin\UsersManagement->printChildUsers()
#2 /home/vu008524/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /home/vu008524/www/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /home/vu008524/www/wp-admin/admin.php(259): do_action()
#5 {main}
  thrown

**Comment by marekdedic** [comment]
Díky za nahlášení, opraveno, vydáme to jako novou verzi :ú

**Comment by marekdedic** [comment]
Vydáno jako 1.1.23
