### ISSUE TITLE
Zobrazování tlačítka "Přihlásit se přes skautIS"

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#15]
@DNepovim narazil na problém se zobrazením tohodle tlačítka

Když dám přihlásit přes skautis tak mi to hodí chybu `Call to a member function getLoginUrl() on null`. Řekl bych že je to tím, že jsem plugin ještě nijak nenastavoval. V takovém případě by se ale asi tlačítko nemělo zobrazovat, ne?

Za mě řešení, šlo by tlačítka na přihlášení skrýt, dokud nebude zadané, nastavené a uložené alespoň jedno APP ID.

Zobecnění: Nezobrazovat nefunkční prvky

**Comment by davidulus** [comment]
Myslím, že je vhodnější ty prvky nechat zobrazené. Nyní to běžné uživatele při nezadaných APP ID přesměruje na úvodní stránku webu. Administrátorovi to zobrazí upozornění a prolinkem do nastavení pluginu. Může být?

**Comment by kalich5** [comment]
Za mě určitě v pohodě. Ještě co na to @DNepovim?

**Comment by DNepovim** [comment]
Za mě určitě ne. Když to tlačítko nefunguje, tak tam nemá co dělat. Přesměrování na homepage člověka dost zmate. Čeká, že se něco stane a stane se něco úplně jiného. Když už, tak by měla vyskočit nějaká srozumitelná zpráva.

**Comment by davidulus** [comment]
Chápu a klidně to tak upravím - jen dám ještě na zvážení proces: když jsem administrátor webu, nainstaluji plugin, podívám se na přihlašovací stránku, vidím tlačítko = je to ok. Kliknu na ně a zjistím, že to není ok a zpráva mi řekne, co mám udělat. Jde o proces nastavování / seznamování správce webu s pluginem.
Uživatelů se tato fáze moc netýká. Nechat si zapnutý plugin, který nenakonfiguruješ a všude Tě to v administraci upozorňuje formou notifikace, není ok přístup a má to přirozené následky ;-) Na webu by prostě tento plugin neměl zůstat aktivovaný v nenastavené podobě.

**Comment by kalich5** [comment]
Taky bych to tak udělal, jak popisuješ Davide. Kdo to nechá zapnutý musí mu to jasně říct, že to má vypnout a nebo smazat.
