### ISSUE TITLE
Shortcode pro vymezení obsahu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#16]
Shortcode pro vymezení obsahu zobrazeného jen při splnění dané sady pravidel. Otevírám debatu, jak to nejlépe vyřešit.

**Comment by kalich5** [comment]
https://cs.wordpress.org/plugins/hide-this/

**Comment by davidulus** [comment]
Jen první nástřel skrz funkčnost - bude to chtít vytvořit ikonu do Tinymce panelu a přidat nastavení pro volbu, zda obsah úplně skrýt nebo zobrazit tlačítko pro přihlášení do skautISu.

**Comment by kalich5** [comment]
Verze i se Shordcody nasazena

**Comment by kalich5** [comment]
A bude u toho možnost přidávat nějak pravidla? Nebo to bude jen skryto, zobrazeno?

**Comment by kalich5** [comment]
Tu lilii bych asi volil spíš černou, té bílé jsem si vůbec nevšimnul.

A to skryto úplně, nebo tlačítko přihlásit se. To se pak bude nastavovat na každé stránce předpokládám...

**Comment by davidulus** [comment]
JJ, velice podobně jako u nastavení viditelnosti - globální výchozí pravidla v nastavení modulu + možnost změny voleb u každého shortcodu zvlášť.

**Comment by davidulus** [comment]
Připravíš please tu tmavou ikonu do Tinymce?

**Comment by kalich5** [comment]
Ikonu připravím, večer pošlu

A to jak jsi popsal to nastavení, takhle za mě super. + to výchozí nastavení, aby bylo vždycky přednastavilo při vytváření nového shordcode
