### ISSUE TITLE
Viditelnost stránknek / příspěvků / custom type 

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#17]
Nastavení viditelnosti stránky / příspěvku / custom type pouze při splnění daných sad pravidel (podobný interface jako nastavení viditelnosti přes heslo)
 Otevírám debatu, jak to nejlépe vyřešit.

**Comment by davidulus** [comment]
Texty a UI ještě není doladěné, ale otestování funkčnosti by mi bodlo :-)

**Comment by kalich5** [comment]
Zkusil jsem to nasadit s touhle novou funkcí. Vypisuje mi to chybu

`
Fatal error: Uncaught TypeError: Argument 1 passed to SkautisIntegration\Modules\Visibility\Admin\Admin::__construct() must be of the type array, boolean given, called in /home/vu009447/www/wp-content/plugins/skautis-integration/src/modules/Visibility/Visibility.php on line 27 and defined in /home/vu009447/www/wp-content/plugins/skautis-integration/src/modules/Visibility/admin/Admin.php:17 Stack trace: #0 /home/vu009447/www/wp-content/plugins/skautis-integration/src/modules/Visibility/Visibility.php(27): SkautisIntegration\Modules\Visibility\Admin\Admin->__construct(false, Object(SkautisIntegration\Rules\RulesManager)) #1 /home/vu009447/www/wp-content/plugins/skautis-integration/src/services/services.php(110): SkautisIntegration\Modules\Visibility\Visibility->__construct(Object(SkautisIntegration\Rules\RulesManager), Object(SkautisIntegration\Auth\SkautisLogin)) #2 /home/vu009447/www/wp-content/plugins/skautis-integration/vendor/pimple/pimple/src/Pimple/Container.php(118): SkautisIntegration\Services\Services::SkautisInte in /home/vu009447/www/wp-content/plugins/skautis-integration/src/modules/Visibility/admin/Admin.php on line 17`
