### ISSUE TITLE
Minimální verze PHP

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#18]
Upravení pluginu pro minimální verzi PHP 7.x

**Comment by kalich5** [comment]
@davidulus Minimální verze PHP 7.x je integrovaná? Podle popisu mi přijde že jo?

**Comment by davidulus** [comment]
Plugin si už hlídá min. verzi PHP, ale kód pro ni ještě není přepsaný.

**Comment by kalich5** [comment]
ok, dík za info
