### ISSUE TITLE
Přiřazování oprávnění pro uživatelské role

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#19]
Nedá se definovat, kdo a jak bude mít k čemu práva. Nedalo by se to tam nějak přidat?

**Comment by davidulus** [comment]
To už mi přijde jako typická věc, která by se měla řešit již hotovými pluginy. Nejlépe asi https://cs.wordpress.org/plugins/user-role-editor/ - vytvořit nové role, přidat do nich požadovaná oprávnění a pak na ně navázat pravidla.

**Comment by davidulus** [comment]
Nebo máš na mysli nějaká konkrétní oprávnění související se správou pluginu?

**Comment by kalich5** [comment]
Vytváření rolí určitě na speciální pluginy. Problém je s těmi oprávněními. Zkoušel jsem to, a pokud nedám admin práva (nedá se ten plugin nastavovat)

**Comment by davidulus** [comment]
Některá práva jsou pevně vázána na 'manage_options'. Na určitých místech je to hookovatelné a dá se to tedy upravit z šablony. Správa pravidel má vlastní sadu oprávnění, která jdou navázat i na jiné role či konkrétní uživatele, právě třeba přes User role editor.
Co ještě myslíš, že by mělo mít vlastní oprávnění, aby se dalo takto přiřazovat? Obecné nastavení a moduly určitě ne - to by mělo být na správci.

**Comment by kalich5** [comment]
No třeba ta správa pravidel se bez manage_options vůbec nezobrazí.

**Comment by davidulus** [comment]
Asi mám špatně provázané zobrazení v menu s oprávněními. Opravím.
Myslíš, že má smysl vytvářet nějaká vlastní oprávnění i pro něco jiného než pravidla?

**Comment by kalich5** [comment]
Tak oprava, v menu se zobrazí. Ale po kliknutí na ní to napíše `Sorry, you are not allowed to access this page.`

**Comment by kalich5** [comment]
Přidal bych pravidlo pro zobrazení "Registrace". Aby ten kdo má právo na pravidla, mohl třeba i upravovat pravidla registace. Zbytech bych nechal jen pro Admina.

**Comment by davidulus** [comment]
No jak tak nad tím přemýšlím, tak to má bezpečnostní úskalí - v registraci by se u takového uživatele muselo omezit, jaké role může přiřazovat. Aby si pak nevytvořil pravidlo, které mu při splnění v registraci umožní získat roli administrátora nebo obecně vyšší roli, než má. A to se rozlišuje dost špatně. Např. když předtím správce přes User role editor přiřadí k nějaké roli nějaká konkrétní vyšší oprávnění nebo si prostě vytvoří novou roli, tak nerozpoznáme, zda má ta role obecně vyšší / nižší oprávnění, než má daný uživatel spravující registraci (pokud není administrátor nebo nemá 'manage_options', pak není co řešit).
Napadá mě řešení - umožnit pouze administrátorovi zvolit role, které budou ve správě registrací k výběru. Tím je odpovědnost převedena plně do rukou administrátora. Co myslíš?

**Comment by davidulus** [comment]
Btw. je to vůbec reálný use case?

**Comment by kalich5** [comment]
Jak nad tím víc a víc přemýšlím, tak nejlepší řešení by bylo tohle...

Celé nastavení i položky v menu uvidí jen Admin. To přihlašování a nastavování je vec kterou by asi měl dělat jen on.

A rekněme si to na rovinu, ty správci skautských webů dávají admin práva kde komu (z mojí zkušenosti), takže je to asi bezpředmětné řešit oprávnění. Převést všechno na admina a je po problému. Myslím, že pluginy typu přihlašování přes FB, Google to mají stejně.

Co myslíš?

**Comment by davidulus** [comment]
OK, za mě souhlas => beze změny :-)

**Comment by kalich5** [comment]
No jediná změna, aby nedalo žádné nastavení toho pluginu zobrazit jinak než když jsi admin. A to teď u těch pravidel jde (i když to nefunguje). 

Takže by bylo nejlepší, aby to z menu zmizelo všem, kromě admina.
