### ISSUE TITLE
Více jazyků - základ v angličtině

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#23]
Vím že to plugin podporuje. Výhledově bych byl pro to, změnit všechny texty na anglické.

Překlad na WordPress org není problém. Už jsem ho tam naklikal https://translate.wordpress.org/projects/wp-plugins/skautis-integration

Co si o tom Davide myslíš?

**Comment by davidulus** [comment]
Chápu, že by to bylo pěkné, ale navrhuji šetřit síly. Plugin má úplně jasnou jazykovou cílovou skupinu už ze své podstaty. Nevidím důvod / přínos pro to, mít jej v angličtině, když to wordpress.org nevadí. To už bych víc pochopil slovenštinu ;-)
Nebo je tu jiný důvod, který mi uniká?

**Comment by kalich5** [comment]
Vycházel jsem z toho, že skautIS měl Anglickou, Českou a Slovenskou mutaci (i když Anglická nebyla dokonalá). Přišlo by mi to dobré na frontendu kde ten web může mít třeba jazykové mutace.
Členy Junáka můžou být teoreticky i cizinci. Je to jen něco navíc, zkusím se kouknout do kódu jak je to tam udělané. Tohle bych možná zvládnul přepsat sám ne?

A po aktualizaci bych jen aktualizoval překlad a bylo byl...

**Comment by davidulus** [comment]
JJ, to zvládneš bez problémů. Nejjednodušší bude hledat řetězce: 'skautis-integration'

**Comment by kalich5** [comment]
Jen přiklad: https://github.com/skaut/skautis-integration/blob/master/skautis-integration.php
řádek: 73
Ten text přepíšu na anglický a dám uložit. A pak při aktualizaci pluginu na WordPress.org se automaticky v Glotpressu přepíše na anglický s možností pro překlad.

Chápu to správně?

**Comment by davidulus** [comment]
jop, jen myslím, že bude potřeba Glosspressu říct, že výchozí jazyk je nyní angličtina a následně mu tedy doplnit české překlady.

**Comment by kalich5** [comment]
Zkusíme to na pár překladech v další verzi. Podle mě se mi překlady jen přehodí do Fuzzy a budu je muset znova schválit. :-)

**Comment by kalich5** [comment]
Tak jsem to zkusil, tady už je angličtina správně: https://skautis-testlogin.skauting.cz/wp-login.php
Ale tady ne: https://skautis-testlogin.skauting.cz/skautis/prihlaseni/

Upravoval jsem tyhle dva soubory
https://github.com/skaut/skautis-integration/blob/master/src/frontend/LoginForm.php
https://github.com/skaut/skautis-integration/blob/master/src/modules/Register/frontend/LoginForm.php

Na co jsem zapomněl?

**Comment by davidulus** [comment]
Na https://skautis-testlogin.skauting.cz/skautis/prihlaseni/ se vykresluje soubor skautis-integration\src\frontend\public\views\login.php - to je ten defaultní, pokud jej nenajde v aktivní šabloně v skautis/login.php

**Comment by kalich5** [comment]
skautis-integration\src\frontend\public\views\login.php a šlo by v tomhle stránce doplnit možnost pro překlad. Teď jak na to koukám, je to jen prostý text.

**Comment by kalich5** [comment]
Když bych to vyměnil za  __( 'Log in with skautIS', 'skautis-integration' ) je to tak správně? Abych věděl pro příště...

**Comment by davidulus** [comment]
JJ, jen je to ještě třeba obalit php tagy a rovnou dát echo (funkce _e() místo __())=>
<?php _e( 'Log in with skautIS', 'skautis-integration' ); ?>

**Comment by davidulus** [comment]
```
<?php _e( 'Log in with skautIS', 'skautis-integration' ); ?>
```

**Comment by kalich5** [comment]
Zrovna jsem chtěl napsat, jestli je to takhle správně
https://github.com/skaut/skautis-integration/blob/master/src/frontend/public/views/login.php

**Comment by davidulus** [comment]
jop :-)

**Comment by kalich5** [comment]
:-) až vydáme verzi 1.1 uvidím jak se to načte v GlotPressu na WP.org. Tam to dopřeložím a ozkouším. Pak tohle issues uzavřu.

**Comment by kalich5** [comment]
AJ řetězce ve frontendu doplněny, překlad do CZ verze vytvořen.
