### ISSUE TITLE
Propojení uživatele

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#28]
Zkusil jsem to na webu. Jsem tam jediný uživatel s admin právy.

Ve svojí záložce jsem dal pro propojit se skautISem. Vyskočí na mě přihlašovací stránka skautISu. Přihlásím se a nic se nestane. Tím pádem nemůžu vytvářet pravidla, ani další věci.

**Comment by davidulus** [comment]
Ve kterém prostředí - testovací / produkční?

**Comment by kalich5** [comment]
Objevil jsem tu chybu v produkčním. Mám už právě APP ID, tak to zkouším.

**Comment by davidulus** [comment]
Nemám jak otestovat produkční prostředí - "Přihlásím se a nic se nestane" - můžeš to více popsat? Kam Tě to přesměruje?

**Comment by davidulus** [comment]
Nějaké záznamy v debug.log?

**Comment by kalich5** [comment]
No prostě mě to přesměruje zpátky na tuhle adresu: https://wpadminpanel.skauting.cz/wp-admin/?ReturnUrl=https%3A%2F%2Fwpadminpanel.skauting.cz%2Fwp-admin%2Fprofile.php%3Fskautis-integration_connectWpAccountWithSkautis%3D97ca215341

**Comment by kalich5** [comment]
A tohle je z acces logu: [06/Jul/2017:20:05:48 +0200] "GET /wp-admin/admin-ajax.php?action=SimpleHistoryNewRowsNotifier&apiArgs%5Bsince_id%5D=14&apiArgs%5Bdates%5D=lastdays%3A30 HTTP/2.0" 200 65 "https://wpadminpanel.skauting.cz/wp-admin/?ReturnUrl=https%3A%2F%2Fwpadminpanel.skauting.cz%2Fwp-admin%2Fprofile.php%3Fskautis-integration_connectWpAccountWithSkautis%3D97ca215341" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

**Comment by kalich5** [comment]
na testovacím webu jsem APP ID zkusil zadat a jede to.  Tam jsou ale nějaká pravidla. Bez pravidel to nepovolí žádné spojení.

**Comment by davidulus** [comment]
Zkus aktualizovat trvalé odkazy, jestli není náhodou chyba v tom: https://wpadminpanel.skauting.cz/wp-admin/options-permalink.php

**Comment by davidulus** [comment]
Propojení uživatele se skautISem u již registrovaných uživatelů, žádná pravidla ani nastavení registrace neřeší. Nedaří se mi to nasimulovat. Tipuji, že to bude souviset s produkčním prostředím, ale pro to nemám žádné APP ID.

**Comment by kalich5** [comment]
Tak na jiném webu to jede v pohodě. Trvalé odkazy jsem zkusil a taky nic.

**Comment by kalich5** [comment]
Zkusím napsat kámošovi, jestli by mi to APP ID nevygeneroval znova. Třeba je chyba v tom. A zjistím, pro jakou jednotku to má vytvořené

**Comment by kalich5** [comment]
Ještě jedna věc, na obou webech kde se to povedlo šlo o MultiSite. Jedině na tom kde to nešlo šlo o klasický WordPress.

**Comment by kalich5** [comment]
bylo to kvůli tomu, že na konci adresy po přihlášení chybělo lomítko "/"
