### ISSUE TITLE
Nejdou zadávat pravidla

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#29]
Při přihlášením přes ostrý skautIS nejdou zadávat pravidla.
<img width="1454" alt="chyba" src="https://user-images.githubusercontent.com/8988898/27928123-46aef1d0-628e-11e7-86ee-9dbc2f54d356.png">

Je to vidět i na testovacím webu. Přidal jsem tam APP ID na ostrý web.

**Comment by davidulus** [comment]
Vzhledem k přidání pravidla pro funkce je potřeba přidat na straně skautISu oprávnění k:
OrganizationUnit->FunctionTypeAll
OrganizationUnit->FunctionAllPerson
V testovacím prostředí je dostupné vše, proto se to projeví až v produkčním.
Předpokládám, že standardní verze 1.0 Ti tuhle chybu nedělá.

**Comment by kalich5** [comment]
Já testuju takový hybrid, proto jsem na tohle přišel. Napsal jsem Sinovi, aby nám to tam přidal.

**Comment by kalich5** [comment]
Bude se muset něco udělat se zadáváním aplikací do skautISu, aby se daly jednoduše a hromadně aktualizovat.

**Comment by kalich5** [comment]
Stále čekám, až mi to SIN nastaví...

**Comment by kalich5** [comment]
Tak tohle všechno tam máme nastavené a ty pravidla se pořád nenačítají

![opravneni externi aplikace __ administrace __ skautis-1](https://user-images.githubusercontent.com/8988898/28157736-b73bf366-67b7-11e7-8fdc-2e476ab7ecc1.png)

**Comment by davidulus** [comment]
Máš možnost dát mi přístup na FTP?

**Comment by kalich5** [comment]
JJ, pošlu ti to emailem...

**Comment by kalich5** [comment]
Tak problém je asi v prohlížeči (Internet Explorer 11) - tam to nefunguje
