### ISSUE TITLE
Do pravidel přidat i možnosti dle členství

### ISSUE THREAD

**Issue by jerrysohn** [skaut/skautis-integration#3]
Pro veřejné používání a propagaci přihlašovacího pluginu skautISu pro WP je nutné, aby v pravidlech bylo možné nastavovat nejen podle skautIS rolí (jak to je dnes a vypadá, že dobře funguje), ale také podle členství. To je totiž ta klíčová funkčnost, kterou budou weby jednotek primárně používat (budou chtít, aby třeba nějaká sekce webu byla dostupná všem členům jejich oddílů, kraje apod.)

Jako nejvhodnější řešení by mi tedy přišlo do stránky správy pravidel přidat podobně jako je tam už dnes "Role (ve skautISu)" i položku "Členství (v jednotce ev. č.)" a k ní:
- operátory: "je rovno" / "začíná na"
- typy členství: "jakékoli" (ve smyslu jakýkoli typ členství ale bez nečlenů) / "řádné" / "čestné" / "hostování" / "nečlen"
- a pak pole pro zadání evidenčního čísla či jeho začátku

A tím bude možné udělat třeba pravidlo:
a) Členství (v jednotce ev. č.) je rovno řádné 513.01.011 => akceptuje všechny řádné členy oddílu 513.01.011
b) Členství (v jednotce ev. č.) začíná jakékoli 51 => akceptuje jakéhokoli člena (řádné, čestné, hostování) kdekoli v Libereckém kraji, tedy evidenční čísla začínající 51...

Zároveň předpokládám zachování možnosti spojování těch pravidel and/or jako je to tam již dnes a tedy v pohodě bude možné poskládat pravidla třeba pro členy několika oddílů apod. dohromady (současně, nebo livovolně "nebo")

Jinak předpokládám, že dnešní možnost "Jednotka (evidenční číslo)" je využívána právě jen ve vztahu k rolím a nedává smysl ji používat pro členství, proto navrhuji tam přidat tu další volbu "Členství (v jednotce ev. č.)"
Jo a ještě poznámka k operátorům u "Jednotka (evidenční číslo)" - pokud se to používá jen pro roli, tak tam asi dává smysl jen "je rovno", nic jiného se myslím nedá využít. A i kdyby se to mělo využívat i pro členství, tak bude opět dávat smysl asi jen "je rovno" a "začíná na". Žádné jiné možnosti nedávají v systému evidenčních čísel v organizaci smysl a ani se to nedá nějak rozumně dovodit z funkcí skautISu, které s evidenčními čísly pracují.

**Comment by davidulus** [comment]
Snad už během dneška nahodím verzi, která toto bude řešit. Ukázal se v souvislosti s tím dost zásadní problém, kterého jsme si nikdo nevšimli - ev. číslo jednotky se nyní ověřuje ve vztahu k aktuální používané roli ve skautISu. Pravidlo role však ověřuje jen obecně, zda uživatel takovou roli má (ne, zda je v ní právě přihlášen). Čili to není s ev. číslem jednotky nijak provázané a zdánlivě to funguje jen proto, že uživatel je v náhodou přihlášen právě v té roli ve vztahu ke správné jednotce.
Nová verze tedy ověří, že uživatel danou roli / role má, ale i jejich vztah ke konkrétní jednotce, což vyžaduje i změnu způsobu zadávání pravidel. V rámci zadávání pravidel rolí přibude k rolím pole pro zadání jednotky (je rovno, začíná na). Musí to být v jednom pravidle.
Samotné pravidlo výběru evidenční jednotky tak bude k ničemu a změním je podobným způsobem na výběr typu členství.
