### ISSUE TITLE
Záložka "Správa uživatelů"

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#30]
Jak přesně funguje ta stránka **Správa uživatelů**

Vidím tam lidi jen ze svého střediska, i když mám ve skautISu roli "Aktivní činovník" pro celou Prahu. Takže vidím členy a jejich podrobnosti pro celou Prahu.

Proč se mi tam teda nenačítají ty ostatní?

**Comment by davidulus** [comment]
Po přepnutí role ve skautISu je potřeba se na webu odhlásit a znovu přihlásit.

**Comment by kalich5** [comment]
A nešlo by nějaký přepínač rolí přidat přímo do WordPressu na tu stránku nahoru doprava? Tohle není úplně user friendly... 

Tím by se dal i ten seznam trochu filtrovat, když tam mám celou Prahu, tak se v tom blbě hledá. Ono obecně nějaké filtrování třeba od 100 záznamů by se hodilo.

**Comment by kalich5** [comment]
Už jsem to nasadil na https://skautis-testlogin.skauting.cz/wp-admin/admin.php?page=skautis-integration_usersManagement

Je to super! :+1: 

Jediné co mi přijde trochu nepřehledné jsou ty šipky pro řazení. Jak jsou na konci sloupce. Klikal jsem na to a myslel jsem že ředím podle přezdívky (a ono to bylo podle jména).

A na konci, by stačilo řazení u "Propojení" v tom posledním sloupci bez popisu to na mě působí divně.
