### ISSUE TITLE
Nejde propojit účet

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#32]
Ani po celkové reinstalaci webu https://wpadminpanel.skauting.cz/ to nefunguje...

https://wpadminpanel.skauting.cz/wp-admin/?ReturnUrl=https%3A%2F%2Fwpadminpanel.skauting.cz%2Fwp-admin%2Fprofile.php%3Fskautis-integration_connectWpAccountWithSkautis%3Da826fb3f6e

Ještě tohle to píše: [10/Jul/2017:21:28:49 +0200] "GET /wp-includes/js/thickbox/loadingAnimation.gif HTTP/2.0" 304 - "https://wpadminpanel.skauting.cz/wp-admin/?ReturnUrl=https%3A%2F%2Fwpadminpanel.skauting.cz%2Fwp-admin%2Fprofile.php%3Fskautis-integration_connectWpAccountWithSkautis%3Da826fb3f6e" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

Nevíš co by to mohlo být... Napadlo mě ještě to, že mám špatné APP ID od Sinuheta

**Comment by davidulus** [comment]
Je to jen záznam z access.log, ten je mi k ničemu. Mrkni, jestli spíš něco není v debug.log (https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG).

V porovnání se skautis-testlogin.skauting.cz - stejné hostingové prostředí, konflikt single site / multi site to není, https vs http také ne, v obou případech jde o produkční verzi APP ID => pokud jsou na obou webech nasazeny aktuální verze kódu - zkoušel bych už jen nastavit stejnou šablonu a pluginy. Pokud problém setrvá - půjde s největší pravděpodobností o problém s APP ID. Konkrétně bych to tipl na klasický problém s těmi redirect adresami pro přihlášení a odhlášení, které se (z pro mě nepochopitelného důvodu) musí u nastavení APP ID zadat.

**Comment by davidulus** [comment]
Pokud Ti tam nefunguje ani registrace - což se vzhledem k přesměrování, které mi to hází zdá - je to problém na straně nastavení APP ID ve skautISu.

**Comment by kalich5** [comment]
Nefunguje vůbec nic, přesměruje mě to na skautIS, ale zpátky to neudělá žádnou akci

**Comment by kalich5** [comment]
Uvidím, až dostanu nové APP ID od SINa... pak dám vědět jak to postupuje

**Comment by kalich5** [comment]
bylo to kvůli tomu, že na konci adresy po přihlášení chybělo lomítko "/"
