### ISSUE TITLE
 Fatal error:  web https://cej2022.cz/

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#323]
Fatal error: Uncaught Skautis_Integration\Vendor\Skautis\InvalidArgumentException: AppId cannot be empty. in /home/vu010657/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Config.php:50 Stack trace: #0 /home/vu010657/www/wp-content/plugins/skautis-integration/src/auth/class-skautis-gateway.php(77): Skautis_Integration\Vendor\Skautis\Config->__construct() #1 /home/vu010657/www/wp-content/plugins/skautis-integration/src/services/class-services.php(192): Skautis_Integration\Auth\Skautis_Gateway->__construct() #2 /home/vu010657/www/wp-content/plugins/skautis-integration/src/services/class-services.php(216): Skautis_Integration\Services\Services::get_skautis_gateway() #3 /home/vu010657/www/wp-content/plugins/skautis-integration/src/services/class-services.php(240): Skautis_Integration\Services\Services::get_skautis_login() #4 /home/vu010657/www/wp-content/plugins/skautis-integration/src/services/class-services.php(278): Skautis_Integration\Services\Services::get_actions() #5 /home/vu010657/www/wp-content/ in /home/vu010657/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Config.php on line 50

**Comment by kalich5** [comment]
Na webu https://oddilartemis.skauting.cz/ stejná chyba...

Fatal error: Uncaught Skautis_Integration\Vendor\Skautis\InvalidArgumentException: AppId cannot be empty. in /home/vu010886/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Config.php:50 Stack trace: #0 /home/vu010886/www/wp-content/plugins/skautis-integration/src/auth/class-skautis-gateway.php(77): Skautis_Integration\Vendor\Skautis\Config->__construct() #1 /home/vu010886/www/wp-content/plugins/skautis-integration/src/services/class-services.php(192): Skautis_Integration\Auth\Skautis_Gateway->__construct() #2 /home/vu010886/www/wp-content/plugins/skautis-integration/src/services/class-services.php(216): Skautis_Integration\Services\Services::get_skautis_gateway() #3 /home/vu010886/www/wp-content/plugins/skautis-integration/src/services/class-services.php(240): Skautis_Integration\Services\Services::get_skautis_login() #4 /home/vu010886/www/wp-content/plugins/skautis-integration/src/services/class-services.php(278): Skautis_Integration\Services\Services::get_actions() #5 /home/vu010886/www/wp-content/ in /home/vu010886/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Config.php on line 50

**Comment by marekdedic** [comment]
Ahoj,
kde to vidíš? Můžeš prosím poslat screenshot? Já to vidím pouze když se pokouším přihlásit ISem bez nastaveného pluginu - což je podle mě správně...

**Comment by kalich5** [comment]
Když ten plugin chci aktivovat... prostě nejde ani zapnout...

**Comment by marekdedic** [comment]
Mně to funguje :D Dokázal bys to prosím někde replikovat?

**Comment by kalich5** [comment]
No na těch webech to nefunguje...

**Comment by kalich5** [comment]
Takže... 
Když Péťa změnila z PHP 7.4 na 8.1 a pluginy jsem přes administraci smazal a znova nainstaloval... tak to funguje

**Comment by marekdedic** [comment]
Zkusím 7.4...

**Comment by kalich5** [comment]
no Péta psala, že jim to přestalo fungovat po aktualizaci... takže předpokládám že asi ano...

**Comment by DeetsCZ** [comment]
@kalich5 ano používali to a po aktualizaci ten plugin zablokoval web. Mám k tomu zjistit ještě nějaké podrobnosti?

**Comment by kalich5** [comment]
Podle mě nemusíš, na všech těch webech pomohla změna PHP, odinstalování a nainstalování... @marekdedic to snad bude stačit, na identifikování problému

**Comment by marekdedic** [comment]
No, tak to různě zkouším aktualizovat tam a zpátky mezi verzemi a furt mi to funguje :/

**Comment by kalich5** [comment]
Po pravdě těžko říct... co tu chybu způsobilo

**Comment by marekdedic** [comment]
Teď jsme opravovali věci okolo App ID, tak tohle zavírám, pokud to ještě někdo bude mít, ať otevře nové issue
