### ISSUE TITLE
Chyba v textu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#34]
![chyba](https://user-images.githubusercontent.com/8988898/28102377-11a2dfe8-66cf-11e7-9b36-839382a593d9.png)

Objevil jsem chybu v textu. Při přidávání **nové Stránky** to dole píše příspěvek. To by chtělo opravit, aby tam bylo správný popis. 

A jak je tam věta: Použít vybraná pravidla i na podřízené příspěvky . (tečka na konci má před sebou mezeru, prosím tu mezeru vyhodit)

**Comment by kalich5** [comment]
![bez nazvu](https://user-images.githubusercontent.com/8988898/28106489-54399d32-66e4-11e7-9291-1f1ba8a06254.png)
To přeci nefunguje jen u příspěvků, ale i u stránek... Je potřeba ten popis zobecnit

Dále když něco vyberu, jako základní nastavení, při založení nového příspěvku, stránky... by to mělo být už dole v nastavení pravidel předvybrané. 

A u příspěvků není potřeba mít podle mě zaškrtávátko pro podřízené, to je jen u stránek. Teda pokud to nefunguje ještě nějak komplexněji

**Comment by davidulus** [comment]
Něco s těmi texty vymyslím, byl to jen nástřel, šlo mi hlavně o funkčnost :-)
U těch příspěvků to má význam u médií. Stránka se zobrazením souboru, která spadá pod daný příspěvek, je pravidly chráněna také (s výjimkou zadání přímo celé URL adresy přílohy v složce wp-content/uploads).
Rozliším ty texty u hierarchických a nehierarchických typů obsahu.

**Comment by kalich5** [comment]
V pohodě, jen jsem si toho všimnul tak jsem to chtěl nějak poznamenat.

Pokud je to u příspěvků k médiím, mělo by tam být něco ve smyslu. "Použít vybraná pravidla i na obsah příspěvku"

Aby bylo jasné, co ta funkce dělá

**Comment by davidulus** [comment]
starter-content nepřistálo ve WP 4.7? https://developer.wordpress.org/reference/functions/add_theme_support/
