### ISSUE TITLE
Nefunguje uzamčení příspěvku

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#35]
http://skautis-testlogin.skauting.cz/
![ok](https://user-images.githubusercontent.com/8988898/28102540-22658bc2-66d0-11e7-80c9-507c483590d4.png)
Tady to funguje

https://skautis-testlogin.skauting.cz/
![nefunguje](https://user-images.githubusercontent.com/8988898/28102553-40910040-66d0-11e7-973c-27034df412c7.png)
Jakmile je před adresou https, už to nefunguje

https://skautis-testlogin.skauting.cz/test/
![pr](https://user-images.githubusercontent.com/8988898/28102569-600fccee-66d0-11e7-8657-506d20236b56.png)
A když ten příspěvek zkusím zobrazit přes odkaz v nadpisu na samostatné stránce, zobrazí se

**Comment by kalich5** [comment]
Tak teď už to na tom testovacím webu je, ještě to budu testovat

**Comment by davidulus** [comment]
Z poslední zprávy jsem trochu zmatený - funguje to nebo ne? :-)

**Comment by kalich5** [comment]
Funguje, nevím proč to ráno nejelo. Nech to být, když by něco napíšu
