### ISSUE TITLE
Chyba na webu - viz e-mail

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#353]
Podrobnosti chyby
=================
Na řádku č. 162 v souboru /home/vu009558/www/wp-content/plugins/skautis-integration/src/admin/class-users-management.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Error: Call to undefined function Skautis_Integration\Admin\str_ends_with() in /home/vu009558/www/wp-content/plugins/skautis-integration/src/admin/class-users-management.php:162
Stack trace:
#0 /home/vu009558/www/wp-includes/class-wp-hook.php(288): Skautis_Integration\Admin\Users_Management::enqueue_scripts_and_styles()
#1 /home/vu009558/www/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters()
#2 /home/vu009558/www/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /home/vu009558/www/wp-admin/admin-header.php(104): do_action()
#4 /home/vu009558/www/wp-admin/admin.php(234): require_once('/home/vu009558/...')
#5 {main}
  thrown

**Comment by marekdedic** [comment]
Closed in #359
