### ISSUE TITLE
Chyba

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#357]
Tak jsem tento plugin dnes aktualizovala zhroutilo mi to administraci webu. V režimu obnovení jsem jej zkusil odinstalovat a nainstalovat znovu a nepomohlo, stále hlásí problém:
Tento plugin se nepodařilo správně načíst a během režimu obnovení byl pozastaven.
Na řádku č. 162 v souboru /home/vu009062/www/wp-content/plugins/skautis-integration/src/admin/class-users-management.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Error: Call to undefined function Skautis_Integration\Admin\str_ends_with() in /home/vu009062/www/wp-content/plugins/skautis-integration/src/admin/class-users-management.php:162 Stack trace: #0 /home/vu009062/www/wp-includes/class-wp-hook.php(287): Skautis_Integration\Admin\Users_Management::enqueue_scripts_and_styles() #1 /home/vu009062/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #2 /home/vu009062/www/wp-includes/plugin.php(478): WP_Hook->do_action() #3 /home/vu009062/www/wp-admin/admin-header.php(104): do_action() #4 /home/vu009062/www/wp-admin/plugins.php(486): require_once('/home/vu009062/...') #5 {main} thrown

**Comment by marekdedic** [comment]
Closed in #359
