### ISSUE TITLE
Přihlašování u uzamčené obsahu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#36]
Sice přihlášení funguje, zobrazí se obsah příspěvku/stránky.

Ale když se chci dostat do administrace musím se znova přihlásit. Předpokládal bych, že když se už jednou přihlásím, budu přihlášen na 100% i v administraci.

**Comment by davidulus** [comment]
Současné zapracování nevyžaduje, aby měl daný uživatel účet ve WP a to považuji za výhodu.
Upravím to tak, aby se to při existenci propojeného účtu ve WP pokusilo přihlásit. Pokud by nebyla splněna pravidla, tak to zůstane přihlášené jen ve skautISu, za běžných okolností by to uživatele odhlásilo i ze skautISu, aby se mohl pokusit připojit s jiným skautIS účtem.

**Comment by kalich5** [comment]
A nebylo by lepší, aby to fungovalo tak že když splní pravidla rovnou mu to i ten účet vytvoří? Přeci jen, aby pak musel znova klikat na přihlášení a registraci není dobré si myslím. Zbytečný krok navíc si myslím.

**Comment by davidulus** [comment]
No nevím, mně se obecně tenhle přístup - registrovat uživatele na webu, aniž by o tom věděl a chtěl - moc nelíbí.

Představ si use case stránky, která má být dostupná pro každého aktivního činovníka kraje - chceš mít ve WP potom registrovaných tolik uživatelů jen kvůli tomu, že si chtěli zobrazit nějakou stránku?
Tak jak to popisuješ by to samozřejmě fungovalo jen při aktivovaném modulu Registrace a i tak může nastat situace, kdy mi uživatel sice splní pravidla pro zobrazení stránky, ale už ne pravidla pro registraci na webu.

Obecně - registrovat uživatele na webu, pokud tam pak nemá spravovat nějaký obsah nebo se tam pro něj neukládají nějaká data jenom pro něj (jeho historie objednávek, apod.) nepovažuji za dobrou cestu.

Za sebe navrhuji mít viditelnosti obsahu oddělené od registrace a přihlášení, tak jak je tomu teď + dopracovat přihlášení do WP, pokud tam má daný skautIS user již propojený účet, aby se ušetřilo to kliknutí navíc.

Nebo to můžeme pořešit volbami v nastavení, jen se tím přidá další složitost, kterou bude třeba popsat v nápovědě.

Prosím tedy v tomto o nějaké final decision a zadání.

**Comment by kalich5** [comment]
Popsání v nápovědě není problém, nějak to napíšu a Mýval ti už přístup udělal, takže když objevíš nějakou chybku budeš to moct opravit.

Nakonec souhlasím s tebou, tak jak to popisuješ.
Pro pouhé zobrazení obsahu, se registrace neudělá. (jak je to teď)
Pokud má ale člověk udělaný už účet, přihlásí ho to i do administrace, aby nemusel klikat znova.

A volby v nastavení by se třeba pro někoho mohli hodit taky. Třeba bude uživatel, který bude chtít aby se při přihlášení rovnou zaregistroval. Potom by ten plugin měl kontrolovat, jestli je zapnutá i registrace, a jestli použitá pravidla jsou i v registraci použitá.
