### ISSUE TITLE
Nefunkční uložení pravidel u stránek

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#361]
U žádné stránky nelze nastavit jakékoli pravidlo. Uloží se, ale po novém načtení adminu uložené není.
Konflikt s jinými pluginy neprobíhá, vyzkoušeno 2x.

**Comment by cupalova** [comment]
"Můžeš nám tam i popsat, jak bys to chtěl používat? Zvažujeme, že necháme pouze možnost skrýt celou stránku a možnost na skrývání nějakých bloků dělat nebudeme."

Skrytí bloků je fajn, například když jsou kontakty a pro veřejnost chceš nechat jen základní, a zbytek pro členy. Nicméně nám nefunguje ani jedno... viz sreen po uložení, výběr zůstane prázdný.
![Snímek obrazovky 2022-10-03 v 14 29 11](https://user-images.githubusercontent.com/114924845/193576835-80c33c8e-2055-425e-9f5f-f103f54608ac.jpg)

**Comment by kalich5** [comment]
A s minulou verzí 1.1.26 to fungovalo v pohodě?

**Comment by cupalova** [comment]
Ne, aktualizovali jsme plugin až dnes, jestli to třeba není novým WP.

**Comment by kalich5** [comment]
On @marekdedic  mi právě psal, že už to asi nefungovalo déle... ale koukne, jak by se to dalo opravit...

**Comment by marekdedic** [comment]
Mělo by být opraveno ve verzi 1.1.28
