### ISSUE TITLE
Odhlášení a zobrazení hlášky

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#38]
Něco jsem objevil, tak se chci optat. Popis situace...

- Jsem přihlášený přes skautIS a v menu kliknu na odhlásit
- Přehodí mě to na login.php stránku
- Kliknu dole na `Zpět: skautIS TEST WEB`
- U příspěvku kde je jen zamčený obsah není vidět login tlačítko, ale píše to `You do not have permission to access this content `

Je tam sice, že k tomu nemám přístup. Ale vlastně není řešení, jak se k tomu dostat. Nešlo by tam taky přidat v takovém případě login tlačítko?

Že by tam bylo...

You do not have permission to access this content 
A pod tím tlačítko, kde by bylo psáno "Pro zobrazení obsahu se musíte přihlásit přes skautIS"

**A druhá situace je, když přijdu na web a nejsem vůbec přihlášený.**
Jediné co je tam v tlačítku napsané je "Log in whit skautIS". Nešlo by tam mít stejnou hlášku, jako v případě co jsem popsal výše?

Co myslíš?

**Comment by davidulus** [comment]
OK, spojím to tak, že bude vždy zobrazená hláška i tlačítko. Pokud jsi přihlášen ve skautISu, ale nemáš dostatečná oprávnění pro zobrazení obsahu - tak Tě kliknutí na tlačítko tedy ze skautISu odhlásí a zobrazí Ti stránku pro přihlášení, aby ses mohl přihlásit s jiným skautIS účtem.

**Comment by kalich5** [comment]
Ano, takhle by to bylo nejlepší

**Comment by davidulus** [comment]
Closed by commit 17144a3620615125af41a19eda948f7eb39ac7bd

**Comment by kalich5** [comment]
nasazeno na testovacím webu

**Comment by kalich5** [comment]
Když zadám adresu webu, hláška se tam nezobrazuje
![bez nazvu0](https://user-images.githubusercontent.com/8988898/28181955-a3bf10ea-680a-11e7-9ca6-11dc13b0721e.png)
Přihlásím se a vrátí se mi tohle (a to jsem admin a tím pádem bych k tomu měl mít přístup ne?) Když se přihlásím přes přihlášení do administrace, obsah se mi zobrazí
![bez nazvu](https://user-images.githubusercontent.com/8988898/28182171-85035b42-680b-11e7-99c1-339e0a13130a.png)

Má se nějaká hláška zobrazovat, i když nejsem přihlášený? Něco jako "Pro zobrazení obsahu je potřeba přihlásit se přes skautIS"
