### ISSUE TITLE
Jméno modulu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#4]
Ještě jak je tam záložka "Moduly" tak je tam teď "Registrace"

Šlo by to změnit na "Přihlášení a registrace" (aby bylo jasné co ten modul dělá)

Děkuju

**Comment by davidulus** [comment]
Modul Registrace se skutečně stará jen o registraci. Po jeho deaktivování není registrace uživatelem možná. Zůstane ovšem možnost přihlašování, včetně tabulky na ruční propojení uživatelů.
Proto navrhuji modul nepřejmenovávat.

**Comment by kalich5** [comment]
Jo tak, já jsem to z toho nepochopil. Jen abychom zamezili otázkám, jestli i bez toho bude přihlášení fungovat.

Nešla by udělat položka nad tím "Přihlášení" kde by byl ten čtvereček zaškrtnutý a šedivý. To by mohlo značit, že přihlášení je nevypnutelné.

Je to jen takový nápad.

**Comment by kalich5** [comment]
Šlo by tu mezeru zmenšit tak na polovinu? 
![oriznuti](https://user-images.githubusercontent.com/8988898/27549887-d796de2c-5a9d-11e7-8735-4875d2a80152.png)
