### ISSUE TITLE
Načítání množství členů při propojení

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#41]
Narazili jsme na problém s množstvím členů, které skautIS povolí načíst. Limit je tam 500.

Na stránce, kde se propojují členi se právě jen 500 načítá. Bylo by dobré, aby fungovalo to hledání mezi členy trochu jinak.

Když zadám do pole pro vyhledávání `ka` tak bych chtěl, aby mi to vracelo všechny členy, kteří ty dvě písmena obsahují. Umí to API vyhledávání? Aby se při tom zadávání do pole "Vyhledávání", aktualizoval seznam lidí v tabulce. 

Šlo by to @jerrysohn

**Comment by jerrysohn** [comment]
Limit na max. 500 záznamů je tam schválně a je globálně (až na speciální výjimky) nad všemi běžnými daty skautISu. A nerad bych to měnil právě na tabulce členů. Naopak právě proto má být nad tou tabulkou používáno hledání, kdy napsané 2 až 3 znaky zajistí ve všech jednotkách, že celá sada vracených osob bude vždy menší než 500 záznamů.
Je tedy potřeba tam mít udělané hledání a ne se snažit vypsat všechny členy najednou (kraje mají tisíce jednotek, středisko Blaník Praha přes 700 členů a není výkonově a ani s ohledem na osobní údaje vhodné to vracet bez jakéhokoliv "filtru=hledání" najednou).

**Comment by kalich5** [comment]
Určitě nechci, aby to vracelo víc jak 500 lidí.
Otázka je spíš na to, jestli se dá přes API umožňuje vyhledávání a opakované načítání. Jestli je tato možnost, tak tím pádem by to byla jen nová funkčnost v pluginu.

**Comment by davidulus** [comment]
Jop, vyhledávání je bez problému.

**Comment by kalich5** [comment]
Dá se to nasadit na testovací web?

**Comment by davidulus** [comment]
Pouze v testovacím prostředí. Pro produkční je třeba přidat:
Events -> EventAllPerson
Events -> EventDetail
Events -> ParticipantGeneralAll
Events -> ParticipantCampAll
Events -> ParticipantEducationAll

**Comment by kalich5** [comment]
Nasazeno na https://skautis-testlogin.skauting.cz/

Koukám, že se nějak změnilo rozhraní, nebo tak se to zobrazuje v Internet Exploreru.

**Comment by kalich5** [comment]
![ds](https://user-images.githubusercontent.com/8988898/28522899-3cc24772-707a-11e7-83fa-94fdbb8c9755.png)

**Comment by davidulus** [comment]
JJ, tabulky jsou teď responzivní a pokud se tam nevlezou všechny sloupce - zobrazí se v této formě. Po rozkliknutí se zobrazí další sloupce. Řeší si to plugin https://datatables.net/

**Comment by kalich5** [comment]
super, dík za info. :-) a koukal jsem, že už se tam dá i vytvořit rovnou učet :-)

**Comment by davidulus** [comment]
Jop, viz ec2325e09b265b7232c7d4e8bdd953481fa2b4fa

**Comment by davidulus** [comment]
Teď už je to dobře použitelné i pro vzdělávací a obecné akce a tábory. Ještě nejsou dořešené sněmy a nové pravidlo Účastník akce.

**Comment by kalich5** [comment]
ok, až to bude vyřešené tak uděláme release, co myslíš?
