### ISSUE TITLE
Změna barvy tlačítek...

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#42]
Nešla by barva i toho tlačítka "Vytvořit nový účet" udělat modrá? Přišlo by mi to tak lepší, jako u toho propojování je modré Potvrdit.
![propojeni_uzivatele](https://user-images.githubusercontent.com/8988898/28747127-0bb47282-7498-11e7-9516-7a447505c6fd.png)

**Comment by davidulus** [comment]
fixed by b0d8e898e5f94262135c1c0b2b3d5410ab4fb92d
