### ISSUE TITLE
Propojování účtů

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#44]
Objevil jsem chybu, při propojování uživatele se skautIS účtem.

Dá se simulovat na https://skautis-testlogin.skauting.cz/ při propojení uživatelů, kteří mají již propojený testovací skautIS. Když kliknu na propojit, přeskočím na úvodní stránku.

**Comment by davidulus** [comment]
Nahrál jsem na https://skautis-testlogin.skauting.cz/ aktuální vývojovou verzi - zkus, jestli to dělá stále. Mně se to tam nepodařilo nasimulovat.
