### ISSUE TITLE
Chyba při prihlášení

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#48]
Docela často se mi stává, že mi WordPress napíše tohle:

``Are you sure you want to do this?``

Nedalo by se to nějak opravit? Nebo zjistit, čím to může být...

**Comment by davidulus** [comment]
Pomohlo by mi vědět, při jakém typu přihlášení se to stává. Při přihlašování do WP, k uzamčenému příspěvku, obsahu (shortcode), při registraci?

**Comment by kalich5** [comment]
Děje se mi to pro přihlášení do WP. Dám wp-admin a pak přihlásit přes skautIS a pak to hodí tohle.

**Comment by davidulus** [comment]
Můžeš mi sem postnout celou URL předtím, než klikneš na tlačítko a potom, co jsi na ně kliknul a vypsalo to chybu?

**Comment by kalich5** [comment]
Určitě, jen se mi to musí povést nasimulovat. Děje se to totiž dost nahodile...

**Comment by davidulus** [comment]
Jak to vypadá?

**Comment by kalich5** [comment]
Zatím se mi to nepovedlo znova nasimulovat. Zatím to neřeš, až se mi to objeví dam to sem.

**Comment by kalich5** [comment]
Kliknul jsem na tlačítko u uzamčeného příspěvku (kde je vidět nadpis) a skočilo na mě tohle: https://skautis-testlogin.skauting.cz/?ReturnUrl=http%3a%2f%2fskautis-testlogin.skauting.cz%2f%3fnoWpLogin%3d1%26skautis-integration_loginToWpBySkautis%3dc6ff5ae7c4

plus: Are you sure you want to do this?

**Comment by kalich5** [comment]
Adresa okna skautISu kde se přihlašuju: https://is.skaut.cz/Login/?appid=cdc9f78a-ea9a-45fd-8c14-93823fd51071&ReturnUrl=http%3A%2F%2Fskautis-testlogin.skauting.cz%2F%3FnoWpLogin%3D1%26skautis-integration_loginToWpBySkautis%3Dc6ff5ae7c4
