### ISSUE TITLE
Odstávka skautISu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#50]
Teď jak je odstávka skautISu, napadlo mě. Nedala by se nějaká jednoduchá hláška (notifikace) ve znění jako je v systému přidat i do prostředí WordPressu? Aby byly uživatelé informovaný, že jim nebude nějakou dobu fungovat přihlášení...

@jerrysohn dá se k té hlášce a jejímu obsahu dostat přes nějakou funkci?

**Comment by jan-stanek** [comment]
Dá se zjistit, že je odstávka pomocí: https://github.com/skaut/Skautis/blob/79d513fcee78038c5a3c0414f5ee43f4d2ee7934/src/Wsdl/WsdlManager.php#L182

**Comment by davidulus** [comment]
Vzhledem k četnosti a délce odstávek považuji za neefektivní k řešení a navrhuji uzavřít @kalich5

**Comment by kalich5** [comment]
ok, s tou hláškou předem je to asi hloupost.

Na druhou stranu by mi přišlo zajímavé, že když by byl skautIS v odstávce, to tlačítko "Přehlásit se přes skautIS" zmizelo. A ta možnost by byla deaktivovaná. Ale nevím, jak náročné to může být na naprogramování.

**Comment by davidulus** [comment]
Jak jsem psal - přijde mi to zbytečné. Kliknu a stejně zjistím, že skautIS má odstávku.
