### ISSUE TITLE
Nezobrazuje se stránka správa uživatelů při špatné roli

### ISSUE THREAD

**Issue by Cactucs** [skaut/skautis-integration#51]
Originál: https://www.facebook.com/photo.php?fbid=600034600387219

> Ahoj,
mám problém s pluginem "skautIS integration", který mi z ničeho nic přestal zobrazovat obsah sekce Správa uživatelů. 
Mám podezření, že by to mohlo být zakliknutím nevhodné uživatelské role SkautISu (pravděpodobně účastník nějakého dávného tábora), nicméně nemám možnost to zvolit spátky (viz screenshot).
Dá se s tím něco dělat?
Díky
Uzlík
![image](https://user-images.githubusercontent.com/4283010/30882556-9adf1710-a309-11e7-92bc-faf294dec4b9.png)

Vyřešeno: 
> Možná můžeš zkusit se přihlásit do skautisu "normálně" na is.skaut.cz, tam změnit roli a potom to zkusit znova tady. To jakou máš zvolenou roli se sdílí mezi skautisem a všemi aplikacemi na něj napojenými.

>Tak už jo, [už to jde]. Nenapadlo mě být při tom odhlášený z toho webu, ale jen jsem refreshoval stránku.

Chtělo by to asi nějakou chybovou hlášku nebo rovnou zkusit člověku změnit roli na nějakou ve které takhle může fungovat.

**Comment by kalich5** [comment]
Tábory a obecně akce se řeší. Bude v nějaké další verzi pluginu. Nemá smysl přidávat teď nějakou hlášku.
