### ISSUE TITLE
Vytváření uživatele

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#52]
Zkouším vytvářet nové uživatele, hodí mi to ale chybu HTTP ERROR 500

A tuhle adresu
https://praha2.skauting.cz/skautis/auth/registerManually?ReturnUrl=https%3A%2F%2Fpraha2.skauting.cz%2Fwp-admin%2Fadmin.php%3Fpage%3Dskautis-integration_usersManagement%26skautisSearchUsers%3DAndy%26skautis-integration_registerToWpBySkautis%3D4250f41251&wpRole=vedouci_obvodu&skautisUserId=852

**Comment by davidulus** [comment]
Je něco zalogováno v debug.log?

**Comment by kalich5** [comment]
[Mon Oct 30 22:35:15.938852 2017] [proxy_fcgi:error] [pid 22967:tid 140270711711488] [client 2a00:1028:919c:f0e:4cc8:2c1f:ccf7:b4d7:55365] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: mb_strcut() expects parameter 1 to be string, null given in /home/vu008555/www/wp-content/plugins/skautis-integration/src/modules/Register/WpRegister.php:92\nStack trace:\n#0 /home/vu008555/www/wp-content/plugins/skautis-integration/src/modules/Register/WpRegister.php(92): mb_strcut(NULL, 0, 60)\n#1 /home/vu008555/www/wp-content/plugins/skautis-integration/src/modules/Register/WpRegister.php(209): SkautisIntegration\\Modules\\Register\\WpRegister->processWpUserRegistration(Array, 'vedouci_obvodu')\n#2 /home/vu008555/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(160): SkautisIntegration\\Modules\\Register\\WpRegister->registerToWpManually('vedouci_obvodu', 852)\n#3 [internal function]: SkautisIntegration\\Modules\\Register\\Register->registerUserManually()\n#4 /home/vu008555/www/wp-content/plugins/skautis-integration/src/general/Actions.php(111): call_user_func(Array)\n#5 /home/vu008555/www/wp-includes/class-wp-hook.php(298): SkautisIntegrat...\n', referer: https://praha2.skauting.cz/wp-admin/admin.php?page=skautis-integration_usersManagement&skautisSearchUsers=Andy

**Comment by kalich5** [comment]
Zkusím zítra, pokud to pojede udělám novou verzi a hodím ji na WP.Org

**Comment by kalich5** [comment]
Už to nekončí chybou, jen to píše...

Uživatele se nepodařilo zaregistrovat

https://praha2.skauting.cz/skautis/auth/registerManually?ReturnUrl=https%3A%2F%2Fpraha2.skauting.cz%2Fwp-admin%2Fadmin.php%3Fpage%3Dskautis-integration_usersManagement%26noWpLogin%3D1%26skautisSearchUsers%3DAndy%26skautis-integration_registerToWpBySkautis%3D8abee06818&wpRole=vedouci_obvodu&skautisUserId=852

**Comment by kalich5** [comment]
V error.log nic není. V access.log je tohle...

[31/Oct/2017:08:08:48 +0100] "GET /wp-content/plugins/skautis-integration/src/modules/Shortcodes/admin/public/img/lilie.png HTTP/2.0" 304 - "https://praha2.skauting.cz/wp-admin/options-general.php?page=seed_csp4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

**Comment by davidulus** [comment]
Jop, to bylo v podstatě jasné, ta předchozí chyba byla způsobena prázdným atributem pro uživatelské jméno, s čímž jsem teda nepočítal => problém je, že skautIS nevrátí uživatelské jméno uživatele... a to by měl :-)
Ještě se na to pořádně podívám, jestli není chyba někde na straně kódu a získávání údajů o uživateli.
Pomohlo by mi - v jaké jsi roli, když daného uživatele přidáváš? Má ten uživatel propojený účet ve skautISu se svojí osobou?
PS: access logy mi do budoucna neposílej, k ničemu mi nepomohou :-)

**Comment by kalich5** [comment]
Pracuju v roli kraj aktivní činovník a ta osoba má propojený účet ve skautISu.

**Comment by kalich5** [comment]
Ještě nějaké info potřebuješ?
