### ISSUE TITLE
Logování přihlašování a odhlašování

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#53]
Našel jsem chybu při logování přihlašování a odhlašování. Ostatní logování přihlašování funguje (FB, Jetpack, WordPress)

Pluginy na kterých jsem to testoval
https://cs.wordpress.org/plugins/simple-history/
https://cs.wordpress.org/plugins/aryo-activity-log/

Mohl by ses na to podívat, v čem je problém? I na testovacím webu jsou oba pluginy instalované.

**Comment by davidulus** [comment]
Opraveno. Vyzkoušeno v Simple History a v pořádku. Activity Log používá stejný přístup, ale problém bude spíš v tom pluginu. Např. vůbec neloguje jiné uživatele než administrátory a nevnímá ani existenci role skautIS. Data do něj v pořádku přijdou, ale do logu to nezapíše. S tím nic neudělám, pakliže to do toho logu nemám vkládat za něj... a to není zrovna nejlepší přístup :-)

**Comment by kalich5** [comment]
ok, ozkouším :-)

**Comment by kalich5** [comment]
Tak někde je asi ještě chybka. Na MultiSite webu to neloguje nic. :-(

**Comment by davidulus** [comment]
Mrknu na to.

**Comment by kalich5** [comment]
Testoval jsem to všude možně, ale nic z toho MultiSite nebyl. Všimnul jsem si toho až na oddílovém webu, že se tam nic nezobrazuje. Při normálním přihlášení přes WordPress účet to jede v pohodě.
