### ISSUE TITLE
Kdo se může přihlásit

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#54]
Jen dotaz, kdo všechno se může přihlásit, když dám pravidlo "Všichni bez omezení"

Dovolí to jen účty, které jsou propojené? A je jasné, že ten kdo se přihlašuje je skaut?

**Comment by davidulus** [comment]
Mělo by to umožnit přihlášení i nepropojeným účtům, ale jak jsem teď zjistil - hází to chybu. Už je to opraveno. Přihlásit se může každý s účtem ve skautISu, který nemusí být propojený s osobou => nemusí to být skaut.

**Comment by kalich5** [comment]
To podle mě není dobře, takhle si může někdo jednoduše vytvořit účet ve skautISu a připojit se na web. Třeba do některých sekcí, které budou jen pro skauty.

Podle mě by to nepropojené lidi nemělo vůbec přihlásit.

**Comment by kalich5** [comment]
@jerrysohn @sinacek co myslíte?

**Comment by kalich5** [comment]
@jerrysohn @sinacek co myslíte?

**Comment by davidulus** [comment]
Stačí říct, upravené je to za chvíli.

**Comment by tomtomklima** [comment]
Já jsem pro to to uzavřít více. Příhlášení je myšleno jako "uzavření neskautské veřejnosti", což je cíl, který teď není plněný.

**Comment by kalich5** [comment]
Tak to tak udělejme, ten kdo nebude mít propojený účet se nepřihlásí a zobrazí se mu hláška že si má účet nechat propojit. 
+ odkaz na návod jak propojit: https://napoveda.skaut.cz/skautis/informacni-system/uzivatel/propojeni-uctu

A každý kdo to bude mít propojený se bude moct přihlásit. A nemusí mít žádnou roli, oddíly to pro členy občas role podle mě nedávají.

**Comment by tomtomklima** [comment]
Za mě ideální přístup
