### ISSUE TITLE
MultiSite

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#6]
Zkoušel jsem aktivovat plugin na multisite webu. Vyskočí takhle hláška.

``Sorry, you are not allowed to access this page.``

Stejná jak v případě aktivace jen na jednom webu, tak i jako síťová instalace.

**Comment by kalich5** [comment]
Pokud to projde, bude možnost tam to lazy-pimple znova přidat ne?

**Comment by davidulus** [comment]
V tuto chvíli již není potřeba.

**Comment by kalich5** [comment]
ok
