### ISSUE TITLE
Nejdou zadávat ani upravovat pravidla

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#62]
V té aktualizaci 1.1.12 je někde asi chybka...
![chyba](https://user-images.githubusercontent.com/8988898/36895368-905d93a2-1e06-11e8-821b-29cf072c385e.png)

**Comment by davidulus** [comment]
Souvisí s nepovolenými službami na úrovni skautISu. V testovacím režimu je to v pořádku.
