### ISSUE TITLE
Moje role - stránka "správa uživatelů"

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#65]
Byl bych pro to, aby se zobrazovaly jen role které mám viditelné ve skautISu.

Teď se zobrazují i skryté a je jich moc. Ta funkce skrývání by se hodila, aby se používala. I další systémy tak fungují. Třeba h.skauting.cz

**Comment by davidulus** [comment]
Hotovo. Release bych kvůli tomu ještě nedělal, ale to nechám na Tobě :-)
