### ISSUE TITLE
Nejde se přihlásit na web přes skautIS

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#728]
Fatal error: Uncaught SoapFault: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Data.SqlClient.SqlException: Externí aplikace 66BA43B1-A373-4EE9-A0A0-F822D0ADF22F (Středisko Polaris ) nemá oprávnění k akci "OU_UnitLocation_ALL"! Při zjištění akcí objektu OU_Unit nastala chyba Při načtení objektů OU_Location nastala chyba at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader() at JunakWebservice.OrganizationUnit.OrganizationUnit.UnitDetail(UnitDetailInput unitDetailInput) in D:\a\1\s\JunakWebservice\OrganizationUnit\UnitDetail.cs:line 41 --- End of inner exception stack trace --- in /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php:77 Stack trace: #0 /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php(77): SoapClient->__soapCall() #1 /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php(48): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->soapCall() #2 /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php(55): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->call() #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/class-func.php(197): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->__call() #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/class-func.php(247): Skautis_Integration\Rules\Rule\Func->getUserFuncsWithUnitIds() #5 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(83): Skautis_Integration\Rules\Rule\Func->is_rule_passed() #6 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(108): Skautis_Integration\Rules\Rules_Manager->process_rule() #7 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(156): Skautis_Integration\Rules\Rules_Manager->parse_rules_groups() #8 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/class-register.php(237): Skautis_Integration\Rules\Rules_Manager->check_if_user_passed_rules_and_get_his_role() #9 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/class-register.php(228): Skautis_Integration\Modules\Register\Register->registerUser() #10 [internal function]: Skautis_Integration\Modules\Register\Register->register() #11 /home/vu008538/www/wp-content/plugins/skautis-integration/src/general/class-actions.php(207): call_user_func() #12 /home/vu008538/www/wp-includes/class-wp-hook.php(324): Skautis_Integration\General\Actions->auth_actions_router() #13 /home/vu008538/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #14 /home/vu008538/www/wp-includes/plugin.php(565): WP_Hook->do_action() #15 /home/vu008538/www/wp-includes/class-wp-query.php(1881): do_action_ref_array() #16 /home/vu008538/www/wp-includes/class-wp-query.php(3824): WP_Query->get_posts() #17 /home/vu008538/www/wp-includes/class-wp.php(696): WP_Query->query() #18 /home/vu008538/www/wp-includes/class-wp.php(816): WP->query_posts() #19 /home/vu008538/www/wp-includes/functions.php(1336): WP->main() #20 /home/vu008538/www/wp-blog-header.php(16): wp() #21 /home/vu008538/www/index.php(17): require('...') #22 {main} Next Skautis_Integration\Vendor\Skautis\Wsdl\WsdlException: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Data.SqlClient.SqlException: Externí aplikace 66BA43B1-A373-4EE9-A0A0-F822D0ADF22F (Středisko Polaris ) nemá oprávnění k akci "OU_UnitLocation_ALL"! Při zjištění akcí objektu OU_Unit nastala chyba Při načtení objektů OU_Location nastala chyba at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader() at JunakWebservice.OrganizationUnit.OrganizationUnit.UnitDetail(UnitDetailInput unitDetailInput) in D:\a\1\s\JunakWebservice\OrganizationUnit\UnitDetail.cs:line 41 --- End of inner exception stack trace --- in /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php:93 Stack trace: #0 /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php(48): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->soapCall() #1 /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php(55): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->call() #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/class-func.php(197): Skautis_Integration\Vendor\Skautis\Wsdl\WebService->__call() #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/class-func.php(247): Skautis_Integration\Rules\Rule\Func->getUserFuncsWithUnitIds() #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(83): Skautis_Integration\Rules\Rule\Func->is_rule_passed() #5 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(108): Skautis_Integration\Rules\Rules_Manager->process_rule() #6 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/class-rules-manager.php(156): Skautis_Integration\Rules\Rules_Manager->parse_rules_groups() #7 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/class-register.php(237): Skautis_Integration\Rules\Rules_Manager->check_if_user_passed_rules_and_get_his_role() #8 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/class-register.php(228): Skautis_Integration\Modules\Register\Register->registerUser() #9 [internal function]: Skautis_Integration\Modules\Register\Register->register() #10 /home/vu008538/www/wp-content/plugins/skautis-integration/src/general/class-actions.php(207): call_user_func() #11 /home/vu008538/www/wp-includes/class-wp-hook.php(324): Skautis_Integration\General\Actions->auth_actions_router() #12 /home/vu008538/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #13 /home/vu008538/www/wp-includes/plugin.php(565): WP_Hook->do_action() #14 /home/vu008538/www/wp-includes/class-wp-query.php(1881): do_action_ref_array() #15 /home/vu008538/www/wp-includes/class-wp-query.php(3824): WP_Query->get_posts() #16 /home/vu008538/www/wp-includes/class-wp.php(696): WP_Query->query() #17 /home/vu008538/www/wp-includes/class-wp.php(816): WP->query_posts() #18 /home/vu008538/www/wp-includes/functions.php(1336): WP->main() #19 /home/vu008538/www/wp-blog-header.php(16): wp() #20 /home/vu008538/www/index.php(17): require('...') #21 {main} thrown in /home/vu008538/www/wp-content/plugins/skautis-integration/vendor/skautis/skautis/src/Wsdl/WebService.php on line 93

**Comment by kalich5** [comment]
A včera to ještě šlo... takže podezřívám novou verzi SkautISu.

**Comment by marekdedic** [comment]
To je možný - je to chyba s nedostatečnými oprávněními ve SkautISu. Ale mně to na mém webu jede, tak aspoň to snad není plošné...
