### ISSUE TITLE
Nemožnost přihlášení

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#80]
Na některých webech jsou problémy s přihlášením. Plugin zahájí přihlášení, odkáže na skautIS, ale po přihlášení hodí chybovou hlášku.

Chyba
Popis: Přihlášení do požadované aplikace nelze dokončit, neboť neodpovídá návratová adresa povolené doméně dané aplikace.

Požadovaná adresa URL: https://is.skaut.cz/Login/default.aspx?appid=64b359ea-894d-47bb-88da-2dbf247bb026&ReturnUrl=https://skautske-tancovani.cz/ples/wp-admin/

Je ale divné, že straně skautISu, jsme vše zkontrolovali a je tam vše nastavené stejně jako u webu https://skautske-tancovani.cz, který je jako hlavní v multisite instalaci. A na něm přihlašování funguje. Ani na jednom webu nejsou nastavená žádná pravidla. 

Podle mě musí být chyba někde v pluginu...

**Comment by davidulus** [comment]
Na multisite jsem poslední úpravy netestoval - mrknu na to. Máš nějaký případ multisite instalace, kde to naopak funguje?

**Comment by kalich5** [comment]
Oddílový web, střediskový web, okresní web, tam to jede v pohodě. Ale tam jsou nastavená pravidla pro přihlašování. Vypadá to na problém, když je Multisite a nejsou tam pravidla. Hlavní web jede, ale ty ...../něco už nejedou.

**Comment by kalich5** [comment]
Problém se z poslední aktualizací API ve skautIS zmizel.
