### ISSUE TITLE
skautis/prihlaseni 404 not found

### ISSUE THREAD

**Issue by lachmanfrantisek** [skaut/skautis-integration#81]
Ahoj,

nasadil jsem wordpress a plugin přes klikátko na https://lebedahosting.cz/admin/account, nastavil APP ID a při kliknutí na `Přihlásit se přes skautIS` mě to hodí na neexistující stránku `skautis/prihlaseni`.

- Verze 1.1.15
- WordPress Verze 5.3.2
- zkoušel jsem vypnout a zapnout plugin i přeinstalování přes rozhraní wordpressu

Mohl by prosím někdo poradit v čem je chyba? Pokud by to pomohlo, jde o `corda tečka skauting tečka cz`.

Předem díky!

Franta

**Comment by marekdedic** [comment]
Ahoj, ta stránka by ve WordPressu měla existovat... (Zkoušel jsem to na `odyssea skauting cz` a hází to na tu samou stránku, která vrací přesměrování do SkautISu). Nemáš tam nějaký bezpečnostní plugin, který by to mohl blokovat?

**Comment by lachmanfrantisek** [comment]
Díky, podívám se. Jak jsem wordpress instaloval automaticky přes lebedu, tak je tam těch pluginů opravdu hodně.

**Comment by kalich5** [comment]
Bezpečnostní plugin tohle nedělá.

1. Koukni se, jestli nemáš v doméně omylem index.php
2. Musíš mít nastavené alespoň jedno pravidlo pro skautIS, aby ti to fungovalo.

**Comment by lachmanfrantisek** [comment]
>     1. Koukni se, jestli nemáš v doméně omylem index.php

Jako v root složce webu? To by jinak nejel wordpress, ne?

>     2\. Musíš mít nastavené alespoň jedno pravidlo pro skautIS, aby ti to fungovalo.

To je záludnější, protože mi to u záložky `Pravidla` píše `Pro správu podmínek je nutné se přihlásit do skautISu`, což nemůžu, protože to nefunguje..;) Jde to nějak obejít?

**Comment by lachmanfrantisek** [comment]
> Nemáš tam nějaký bezpečnostní plugin, který by to mohl blokovat?

Zkoušel jsem povypínat kde co a bez úspěchu.

**Comment by kalich5** [comment]
Napiš nám na kontakt@dobryweb.skauting.cz koukneme se na to.

**Comment by lachmanfrantisek** [comment]
Díky  @kalich5 za zprovoznění -- je potřeba smazat `index.php` z pevných odkazů na následující stránce:

https://moje-domena/wp-admin/options-permalink.php
