### ISSUE TITLE
PHP 7.4 deprecation warning

### ISSUE THREAD

**Issue by marekdedic** [skaut/skautis-integration#82]
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /.../wp-content/plugins/skautis-integration/src/rules/Revisions.php on line 25`

**Comment by kalich5** [comment]
@davidulus koukni na to prosím, děkuji

**Comment by kalich5** [comment]
@marekdedic tohle už je opravené?

**Comment by marekdedic** [comment]
Ano, opraveno v #90
