### ISSUE TITLE
Závažné problémy co generuje plugin

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#85]
WordPress má už nějakou dobu v sobě integrovaný kontrolu stavy webu a tenhle plugin generuje 3 závažné chyby.

1. An active PHP session detected
A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.

2. V REST API došlo k chybě
REST API je jeden ze způsobů, jak WordPress a další aplikace komunikují se serverem. Jedním z příkladů je obrazovka editoru, která se o toto API opírá při zobrazování a ukládání příspěvků a stránek.

REST API požadavek selhal z důvodu chyby.
Error: cURL error 28: Operation timed out after 10002 milliseconds with 0 bytes received (http_request_failed)

3. Web nemohl dokončit požadavek zpětné smyčky
Požadavky zpětné smyčky slouží ke spouštění naplánovaných událostí a jsou také používány vestavěnými editory pro ověření stability kódu šablon a pluginů.

Požadavek zpětné smyčky na váš web selhal, funkce, které na ně spoléhají, momentálně nefungují očekávaným způsobem.
Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (http_request_failed)

@davidulus prosím, kouknu na to co to má být. Chtělo by to opravit.

**Comment by kalich5** [comment]
@marekdedic tohle už je opraveno co?

**Comment by marekdedic** [comment]
jj, to je vyřešeno v #106
