### ISSUE TITLE
Služby ve skautISu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#9]
Můžeš se jen podívat na tenhle seznam. Jestli je ten plugin všechny používá. Předpokládám že jo, ale abych měl jistotu. Děkuju

https://github.com/skaut/skautis-integration/blob/master/APP%20ID%20-%20povolen%C3%AD%20slu%C5%BEeb.md

**Comment by davidulus** [comment]
Používám k přístupu přes skautIS knihovnu https://github.com/skaut/Skautis dle domluvy. Přes ní volám tyto metody:
OrganizationUnit->UnitDetail
OrganizationUnit->MembershipTypeAll
OrganizationUnit->MembershipAllPerson
OrganizationUnit->PersonDetail

UserManagement->UserDetail
UserManagement->userAll
UserManagement->RoleAll
UserManagement->UserRoleAll

Ale dopodrobna zkoumat, co volá ta knihovna na pozadí, opravdu nehodlám :-)

**Comment by sinacek** [comment]
tenhle seznam je přesně to co jsem potřeboval
